name: fitzface
version: 0.0.1
description: >-
  Fitzface blog
homepage: https://blog.fitzface.dev
documentation: https://github.com/afitz0/blog.fitzface.dev
environment:
  sdk: '>=2.10.0 <3.0.0'
dependencies: 
  front_matter: ^1.1.0
  jael3: ^4.0.0
  markdown: ^4.0.0
  path: ^1.8.0
